version: "3.3"
services:
  app:
    image: ericfatec/apidockerized:latest
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "5000:5000"
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dadosensores
      MYSQL_USER: estufa
      MYSQL_PASSWORD: estufa
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD","mysql","-h","localhost","-uestufa","-pestufa","-e","SELECT 1"]
      interval: 10s
      retries: 5